# Server Port
server.port=8080

# Database Connection
# IMPORTANT: Make sure you create an empty database named 'moolgranth_db' in your MySQL!
spring.datasource.url=jdbc:mysql://localhost:3306/moolgranth_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# Hibernate Setup (Automatically creates tables based on our Java classes)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect